notifications:
  email: false

language: python
python:
  - "2.7"

cache: pip

git:
  depth: 1

install:
  - pip install coveralls
  - pip install nose
  - pip install .
  
script:
  - make test

after_success:
  coveralls