notifications:
  email: false

language: python
python:
  -  "2.7"

git:
  depth: 1

install:
  - pip install coveralls
  - pip install nose
  - pip install .
  
script:
  - nosetests --with-coverage --cover-package opendir_dl tests/

after_success:
  coveralls