notifications:
  email: false

language: python
python:
  - "2.7"

cache:
  directories:
   - "$HOME/.cache/pip"

git:
  depth: 1

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .

script:
  - make test

after_success:
  coveralls
