notifications:
  email: false

language: python
python:
  -  "2.7"

git:
  depth: 1

install:
  - pip install coveralls
  - pip install nose
  - pip install .
  
script:
  - nosetests tests/
  - coverage run -m unittest tests.test_utils

after_success:
  coveralls